In [76]:
from md import *

In [77]:
data=pd.read_csv('LOG_DATA.csv')

In [78]:
data

,MASTERLOG_ID,MSG_DATETIME,MSG_STATUS,HUB_CNT,SPOKE_CNT,RECV_HUB_CNT,RECV_SPOKE_CNT,ERROR_TYPE,ERROR_CNT,REASON_CODE,...,COMPRESS_SIZE,SOURCE_DIR_NM,SOURCE_FILE_NM,TARGET_DIR_NM,TARGET_FILE_NM,RECORD_S_CNT,RECORD_E_CNT,P_TIME,GLOBAL_ID,RECV_HOST_ID
0,19,20181101000125600000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:01.8,NaN,NaN
1,19,20181101000143000000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:08.1,NaN,NaN
2,19,20181101000144700000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:17.3,NaN,NaN
3,19,20181101000241200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:06.8,NaN,NaN
4,19,20181101000248600000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.4,NaN,NaN
5,19,20181101000817200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:06.2,NaN,NaN
6,19,20181101000823300000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:11.0,NaN,NaN
7,19,20181101000955200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:13.9,NaN,NaN
8,19,20181101001403800000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:09.7,NaN,NaN
9,19,20181101001528400000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:08.9,NaN,NaN
10,19,20181101001618400000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:14.0,NaN,NaN
11,19,20181101001624600000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:08.1,NaN,NaN
12,19,20181101001642700000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:11.1,NaN,NaN
13,19,20181101001657100000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.7,NaN,NaN
14,19,20181101002122300000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:06.6,NaN,NaN
15,19,20181101002351300000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:17.5,NaN,NaN
16,19,20181101002407400000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:13.5,NaN,NaN
17,19,20181101002509500000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.7,NaN,NaN
18,19,20181101002820200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:11.8,NaN,NaN
19,19,20181101002833300000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:01.6,NaN,NaN
20,19,20181101002937000000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:13.4,NaN,NaN
21,19,20181101003131400000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:09.1,NaN,NaN
22,19,20181101003142400000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:07.8,NaN,NaN
23,19,20181101003220300000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:13.1,NaN,NaN
24,19,20181101003400800000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.4,NaN,NaN
25,19,20181101003443900000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:04.7,NaN,NaN
26,19,20181101003445000000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:11.0,NaN,NaN
27,19,20181101003547400000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:13.9,NaN,NaN
28,19,20181101003549200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:07.3,NaN,NaN
29,19,20181101004137300000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43200,19,20181130233211100000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:08.2,NaN,NaN
43201,19,20181130233501200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:13.2,NaN,NaN
43202,19,20181130233533600000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:19.8,NaN,NaN
43203,19,20181130233609200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.7,NaN,NaN
43204,19,20181130233716200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:12.5,NaN,NaN
43205,19,20181130233725800000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:22.0,NaN,NaN
43206,19,20181130233733100000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:19.1,NaN,NaN
43207,19,20181130233819200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:29.7,NaN,NaN
43208,19,20181130233852400000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:21.8,NaN,NaN
43209,19,20181130233901500000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:02.8,NaN,NaN
43210,19,20181130234116200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.0,NaN,NaN
43211,19,20181130234148800000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:17.7,NaN,NaN
43212,19,20181130234213500000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.1,NaN,NaN
43213,19,20181130234228100000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:16.1,NaN,NaN
43214,19,20181130234425100000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:24.2,NaN,NaN
43215,19,20181130234633800000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:18.0,NaN,NaN
43216,19,20181130234638900000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:28.3,NaN,NaN
43217,19,20181130234745000000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.8,NaN,NaN
43218,19,20181130235206600000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:19.8,NaN,NaN
43219,19,20181130235253800000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:17.4,NaN,NaN
43220,19,20181130235342200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:23.1,NaN,NaN
43221,19,20181130235556800000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:21.4,NaN,NaN
43222,19,20181130235649200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:15.1,NaN,NaN
43223,19,20181130235706300000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:21.6,NaN,NaN
43224,19,20181130235708100000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:14.9,NaN,NaN
43225,19,20181130235727200000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:26.5,NaN,NaN
43226,19,20181130235748100000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:19.6,NaN,NaN
43227,19,20181130235834100000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:22.0,NaN,NaN
43228,19,20181130235853100000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:25.8,NaN,NaN
43229,19,20181130235933400000,0,0,1,1,1,NaN,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:15.1,NaN,NaN

In [79]:
data['P_TIME']

0        00:01.8
1        00:08.1
2        00:17.3
3        00:06.8
4        00:10.4
5        00:06.2
6        00:11.0
7        00:13.9
8        00:09.7
9        00:08.9
10       00:14.0
11       00:08.1
12       00:11.1
13       00:10.7
14       00:06.6
15       00:17.5
16       00:13.5
17       00:10.7
18       00:11.8
19       00:01.6
20       00:13.4
21       00:09.1
22       00:07.8
23       00:13.1
24       00:10.4
25       00:04.7
26       00:11.0
27       00:13.9
28       00:07.3
29       00:10.4
          ...
43200    00:08.2
43201    00:13.2
43202    00:19.8
43203    00:20.7
43204    00:12.5
43205    00:22.0
43206    00:19.1
43207    00:29.7
43208    00:21.8
43209    00:02.8
43210    00:10.0
43211    00:17.7
43212    00:10.1
43213    00:16.1
43214    00:24.2
43215    00:18.0
43216    00:28.3
43217    00:20.8
43218    00:19.8
43219    00:17.4
43220    00:23.1
43221    00:21.4
43222    00:15.1
43223    00:21.6
43224    00:14.9
43225    00:26.5
43226    00:19.6
43227    00:22.0
43228    00:25.8
43229    00:15.1
Name: P_TIME, Length: 43230, dtype: object

In [80]:
data.columns

Index(['MASTERLOG_ID', 'MSG_DATETIME', 'MSG_STATUS', 'HUB_CNT', 'SPOKE_CNT',
       'RECV_HUB_CNT', 'RECV_SPOKE_CNT', 'ERROR_TYPE', 'ERROR_CNT',
       'REASON_CODE', 'MSG_TTL', 'MSG_ALERT', 'RECORD_CNT', 'ADAPTER_CODE',
       'RECORD_SIZE', 'DATA_SIZE', 'COMPRESS_YN', 'COMPRESS_SIZE',
       'SOURCE_DIR_NM', 'SOURCE_FILE_NM', 'TARGET_DIR_NM', 'TARGET_FILE_NM',
       'RECORD_S_CNT', 'RECORD_E_CNT', 'P_TIME', 'GLOBAL_ID', 'RECV_HOST_ID'],
      dtype='object')

In [81]:
data['P_TIME'][0].replace('00:','')

'01.8'

In [82]:
label=pd.DataFrame(np.ones([len(data),1]),columns=['label'])

In [83]:
labeled_data=pd.concat([label,data],axis=1)

In [84]:
labeled_data['label']

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
5        1.0
6        1.0
7        1.0
8        1.0
9        1.0
10       1.0
11       1.0
12       1.0
13       1.0
14       1.0
15       1.0
16       1.0
17       1.0
18       1.0
19       1.0
20       1.0
21       1.0
22       1.0
23       1.0
24       1.0
25       1.0
26       1.0
27       1.0
28       1.0
29       1.0
        ...
43200    1.0
43201    1.0
43202    1.0
43203    1.0
43204    1.0
43205    1.0
43206    1.0
43207    1.0
43208    1.0
43209    1.0
43210    1.0
43211    1.0
43212    1.0
43213    1.0
43214    1.0
43215    1.0
43216    1.0
43217    1.0
43218    1.0
43219    1.0
43220    1.0
43221    1.0
43222    1.0
43223    1.0
43224    1.0
43225    1.0
43226    1.0
43227    1.0
43228    1.0
43229    1.0
Name: label, Length: 43230, dtype: float64

In [85]:
labeled_data.columns

Index(['label', 'MASTERLOG_ID', 'MSG_DATETIME', 'MSG_STATUS', 'HUB_CNT',
       'SPOKE_CNT', 'RECV_HUB_CNT', 'RECV_SPOKE_CNT', 'ERROR_TYPE',
       'ERROR_CNT', 'REASON_CODE', 'MSG_TTL', 'MSG_ALERT', 'RECORD_CNT',
       'ADAPTER_CODE', 'RECORD_SIZE', 'DATA_SIZE', 'COMPRESS_YN',
       'COMPRESS_SIZE', 'SOURCE_DIR_NM', 'SOURCE_FILE_NM', 'TARGET_DIR_NM',
       'TARGET_FILE_NM', 'RECORD_S_CNT', 'RECORD_E_CNT', 'P_TIME', 'GLOBAL_ID',
       'RECV_HOST_ID'],
      dtype='object')

In [86]:
for i in range(len(data)):
    if float(data['P_TIME'][i].replace('00:','')) > 20:
        labeled_data['label'][i]=0

C:\ProgramData\Anaconda3\envs\mp\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [87]:
labeled_data[labeled_data['label']==0]

,label,MASTERLOG_ID,MSG_DATETIME,MSG_STATUS,HUB_CNT,SPOKE_CNT,RECV_HUB_CNT,RECV_SPOKE_CNT,ERROR_TYPE,ERROR_CNT,...,COMPRESS_SIZE,SOURCE_DIR_NM,SOURCE_FILE_NM,TARGET_DIR_NM,TARGET_FILE_NM,RECORD_S_CNT,RECORD_E_CNT,P_TIME,GLOBAL_ID,RECV_HOST_ID
41790,0.0,19,20181130000109100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:25.5,NaN,NaN
41792,0.0,19,20181130000500700000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.8,NaN,NaN
41793,0.0,19,20181130000621400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:25.7,NaN,NaN
41794,0.0,19,20181130000653700000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:25.0,NaN,NaN
41796,0.0,19,20181130000736500000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:25.0,NaN,NaN
41798,0.0,19,20181130000938900000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:24.6,NaN,NaN
41799,0.0,19,20181130001006400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:30.8,NaN,NaN
41801,0.0,19,20181130001121200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:22.9,NaN,NaN
41802,0.0,19,20181130001132000000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.6,NaN,NaN
41803,0.0,19,20181130001408200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.9,NaN,NaN
41804,0.0,19,20181130001456300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:24.2,NaN,NaN
41805,0.0,19,20181130001500100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:29.3,NaN,NaN
41807,0.0,19,20181130001602500000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:29.4,NaN,NaN
41808,0.0,19,20181130001704000000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:28.7,NaN,NaN
41810,0.0,19,20181130001845200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:24.4,NaN,NaN
41811,0.0,19,20181130001908500000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:24.9,NaN,NaN
41812,0.0,19,20181130002119100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.3,NaN,NaN
41816,0.0,19,20181130002438400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:23.0,NaN,NaN
41818,0.0,19,20181130002532200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:21.1,NaN,NaN
41822,0.0,19,20181130003400700000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:22.9,NaN,NaN
41823,0.0,19,20181130003843700000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:26.7,NaN,NaN
41826,0.0,19,20181130003911400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:24.5,NaN,NaN
41830,0.0,19,20181130004229400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:27.9,NaN,NaN
41833,0.0,19,20181130004509000000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:23.8,NaN,NaN
41838,0.0,19,20181130005008000000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.2,NaN,NaN
41840,0.0,19,20181130005125100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:29.4,NaN,NaN
41843,0.0,19,20181130005258000000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:28.8,NaN,NaN
41844,0.0,19,20181130005413300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:21.9,NaN,NaN
41849,0.0,19,20181130005903800000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:28.3,NaN,NaN
41850,0.0,19,20181130005905000000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:22.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43160,0.0,19,20181130225328400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:31.2,NaN,NaN
43162,0.0,19,20181130225443900000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.9,NaN,NaN
43163,0.0,19,20181130225505600000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:27.3,NaN,NaN
43164,0.0,19,20181130225520400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:28.6,NaN,NaN
43170,0.0,19,20181130230120800000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:34.2,NaN,NaN
43172,0.0,19,20181130230403300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:24.4,NaN,NaN
43173,0.0,19,20181130230613300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:34.2,NaN,NaN
43178,0.0,19,20181130231109700000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:24.3,NaN,NaN
43179,0.0,19,20181130231235800000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:22.0,NaN,NaN
43184,0.0,19,20181130231513400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:26.8,NaN,NaN
43185,0.0,19,20181130231537200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:24.9,NaN,NaN
43188,0.0,19,20181130231635300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:28.2,NaN,NaN
43189,0.0,19,20181130231952400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:21.5,NaN,NaN
43190,0.0,19,20181130231958900000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.8,NaN,NaN
43191,0.0,19,20181130232016000000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:28.3,NaN,NaN
43198,0.0,19,20181130232959700000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:29.6,NaN,NaN
43199,0.0,19,20181130233054600000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:32.1,NaN,NaN
43203,0.0,19,20181130233609200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.7,NaN,NaN
43205,0.0,19,20181130233725800000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:22.0,NaN,NaN
43207,0.0,19,20181130233819200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:29.7,NaN,NaN
43208,0.0,19,20181130233852400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:21.8,NaN,NaN
43214,0.0,19,20181130234425100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:24.2,NaN,NaN
43216,0.0,19,20181130234638900000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:28.3,NaN,NaN
43217,0.0,19,20181130234745000000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.8,NaN,NaN
43220,0.0,19,20181130235342200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:23.1,NaN,NaN
43221,0.0,19,20181130235556800000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:21.4,NaN,NaN
43223,0.0,19,20181130235706300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:21.6,NaN,NaN
43225,0.0,19,20181130235727200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:26.5,NaN,NaN
43227,0.0,19,20181130235834100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:22.0,NaN,NaN
43228,0.0,19,20181130235853100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:25.8,NaN,NaN

In [88]:
labeled_data

,label,MASTERLOG_ID,MSG_DATETIME,MSG_STATUS,HUB_CNT,SPOKE_CNT,RECV_HUB_CNT,RECV_SPOKE_CNT,ERROR_TYPE,ERROR_CNT,...,COMPRESS_SIZE,SOURCE_DIR_NM,SOURCE_FILE_NM,TARGET_DIR_NM,TARGET_FILE_NM,RECORD_S_CNT,RECORD_E_CNT,P_TIME,GLOBAL_ID,RECV_HOST_ID
0,1.0,19,20181101000125600000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:01.8,NaN,NaN
1,1.0,19,20181101000143000000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:08.1,NaN,NaN
2,1.0,19,20181101000144700000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:17.3,NaN,NaN
3,1.0,19,20181101000241200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:06.8,NaN,NaN
4,1.0,19,20181101000248600000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.4,NaN,NaN
5,1.0,19,20181101000817200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:06.2,NaN,NaN
6,1.0,19,20181101000823300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:11.0,NaN,NaN
7,1.0,19,20181101000955200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:13.9,NaN,NaN
8,1.0,19,20181101001403800000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:09.7,NaN,NaN
9,1.0,19,20181101001528400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:08.9,NaN,NaN
10,1.0,19,20181101001618400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:14.0,NaN,NaN
11,1.0,19,20181101001624600000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:08.1,NaN,NaN
12,1.0,19,20181101001642700000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:11.1,NaN,NaN
13,1.0,19,20181101001657100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.7,NaN,NaN
14,1.0,19,20181101002122300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:06.6,NaN,NaN
15,1.0,19,20181101002351300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:17.5,NaN,NaN
16,1.0,19,20181101002407400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:13.5,NaN,NaN
17,1.0,19,20181101002509500000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.7,NaN,NaN
18,1.0,19,20181101002820200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:11.8,NaN,NaN
19,1.0,19,20181101002833300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:01.6,NaN,NaN
20,1.0,19,20181101002937000000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:13.4,NaN,NaN
21,1.0,19,20181101003131400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:09.1,NaN,NaN
22,1.0,19,20181101003142400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:07.8,NaN,NaN
23,1.0,19,20181101003220300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:13.1,NaN,NaN
24,1.0,19,20181101003400800000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.4,NaN,NaN
25,1.0,19,20181101003443900000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:04.7,NaN,NaN
26,1.0,19,20181101003445000000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:11.0,NaN,NaN
27,1.0,19,20181101003547400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:13.9,NaN,NaN
28,1.0,19,20181101003549200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:07.3,NaN,NaN
29,1.0,19,20181101004137300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43200,1.0,19,20181130233211100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:08.2,NaN,NaN
43201,1.0,19,20181130233501200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:13.2,NaN,NaN
43202,1.0,19,20181130233533600000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:19.8,NaN,NaN
43203,0.0,19,20181130233609200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.7,NaN,NaN
43204,1.0,19,20181130233716200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:12.5,NaN,NaN
43205,0.0,19,20181130233725800000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:22.0,NaN,NaN
43206,1.0,19,20181130233733100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:19.1,NaN,NaN
43207,0.0,19,20181130233819200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:29.7,NaN,NaN
43208,0.0,19,20181130233852400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:21.8,NaN,NaN
43209,1.0,19,20181130233901500000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:02.8,NaN,NaN
43210,1.0,19,20181130234116200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.0,NaN,NaN
43211,1.0,19,20181130234148800000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:17.7,NaN,NaN
43212,1.0,19,20181130234213500000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:10.1,NaN,NaN
43213,1.0,19,20181130234228100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:16.1,NaN,NaN
43214,0.0,19,20181130234425100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:24.2,NaN,NaN
43215,1.0,19,20181130234633800000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:18.0,NaN,NaN
43216,0.0,19,20181130234638900000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:28.3,NaN,NaN
43217,0.0,19,20181130234745000000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:20.8,NaN,NaN
43218,1.0,19,20181130235206600000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:19.8,NaN,NaN
43219,1.0,19,20181130235253800000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:17.4,NaN,NaN
43220,0.0,19,20181130235342200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:23.1,NaN,NaN
43221,0.0,19,20181130235556800000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:21.4,NaN,NaN
43222,1.0,19,20181130235649200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:15.1,NaN,NaN
43223,0.0,19,20181130235706300000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:21.6,NaN,NaN
43224,1.0,19,20181130235708100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:14.9,NaN,NaN
43225,0.0,19,20181130235727200000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:26.5,NaN,NaN
43226,1.0,19,20181130235748100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:19.6,NaN,NaN
43227,0.0,19,20181130235834100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:22.0,NaN,NaN
43228,0.0,19,20181130235853100000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:25.8,NaN,NaN
43229,1.0,19,20181130235933400000,0,0,1,1,1,NaN,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,00:15.1,NaN,NaN

# 2번

In [ ]:
df=labeled_data[['label','MSG_DATETIME','P_TIME']]

In [ ]:
df

In [ ]:
p_time=pd.DataFrame(np.zeros([len(df),1]),columns=['p_time'])

In [ ]:
p_time

In [ ]:
df=pd.concat([df,p_time],axis=1)

In [ ]:
df

In [91]:


for i in range(len(df)):
  df['p_time'][i]=float(df['P_TIME'][i].replace('00:',''))

C:\ProgramData\Anaconda3\envs\mp\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [92]:
df.re

       label           MSG_DATETIME   P_TIME  p_time
0        1.0  20181101000125600000   00:01.8     1.8
1        1.0  20181101000143000000   00:08.1     8.1
2        1.0  20181101000144700000   00:17.3    17.3
3        1.0  20181101000241200000   00:06.8     6.8
4        1.0  20181101000248600000   00:10.4    10.4
5        1.0  20181101000817200000   00:06.2     6.2
6        1.0  20181101000823300000   00:11.0    11.0
7        1.0  20181101000955200000   00:13.9    13.9
8        1.0  20181101001403800000   00:09.7     9.7
9        1.0  20181101001528400000   00:08.9     8.9
10       1.0  20181101001618400000   00:14.0    14.0
11       1.0  20181101001624600000   00:08.1     8.1
12       1.0  20181101001642700000   00:11.1    11.1
13       1.0  20181101001657100000   00:10.7    10.7
14       1.0  20181101002122300000   00:06.6     6.6
15       1.0  20181101002351300000   00:17.5    17.5
16       1.0  20181101002407400000   00:13.5    13.5
17       1.0  20181101002509500000   00:10.7    10.7
18       1.0  20181101002820200000   00:11.8    11.8
19       1.0  20181101002833300000   00:01.6     1.6
20       1.0  20181101002937000000   00:13.4    13.4
21       1.0  20181101003131400000   00:09.1     9.1
22       1.0  20181101003142400000   00:07.8     7.8
23       1.0  20181101003220300000   00:13.1    13.1
24       1.0  20181101003400800000   00:10.4    10.4
25       1.0  20181101003443900000   00:04.7     4.7
26       1.0  20181101003445000000   00:11.0    11.0
27       1.0  20181101003547400000   00:13.9    13.9
28       1.0  20181101003549200000   00:07.3     7.3
29       1.0  20181101004137300000   00:10.4    10.4
...      ...                    ...      ...     ...
43200    1.0  20181130233211100000   00:08.2     8.2
43201    1.0  20181130233501200000   00:13.2    13.2
43202    1.0  20181130233533600000   00:19.8    19.8
43203    0.0  20181130233609200000   00:20.7    20.7
43204    1.0  20181130233716200000   00:12.5    12.5
43205    0.0  20181130233725800000   00:22.0    22.0
43206    1.0  20181130233733100000   00:19.1    19.1
43207    0.0  20181130233819200000   00:29.7    29.7
43208    0.0  20181130233852400000   00:21.8    21.8
43209    1.0  20181130233901500000   00:02.8     2.8
43210    1.0  20181130234116200000   00:10.0    10.0
43211    1.0  20181130234148800000   00:17.7    17.7
43212    1.0  20181130234213500000   00:10.1    10.1
43213    1.0  20181130234228100000   00:16.1    16.1
43214    0.0  20181130234425100000   00:24.2    24.2
43215    1.0  20181130234633800000   00:18.0    18.0
43216    0.0  20181130234638900000   00:28.3    28.3
43217    0.0  20181130234745000000   00:20.8    20.8
43218    1.0  20181130235206600000   00:19.8    19.8
43219    1.0  20181130235253800000   00:17.4    17.4
43220    0.0  20181130235342200000   00:23.1    23.1
43221    0.0  20181130235556800000   00:21.4    21.4
43222    1.0  20181130235649200000   00:15.1    15.1
43223    0.0  20181130235706300000   00:21.6    21.6
43224    1.0  20181130235708100000   00:14.9    14.9
43225    0.0  20181130235727200000   00:26.5    26.5
43226    1.0  20181130235748100000   00:19.6    19.6
43227    0.0  20181130235834100000   00:22.0    22.0
43228    0.0  20181130235853100000   00:25.8    25.8
43229    1.0  20181130235933400000   00:15.1    15.1

[43230 rows x 4 columns]

In [94]:
df.to_csv('dffff.csv',mode='w')

In [ ]:
df['p_time']=log

In [95]:
df2=df[['MSG_DATETIME','p_time']]

In [109]:
time(int(df2['MSG_DATETIME'][0]))

Wall time: 0 ns

20181101000125600000

In [110]:
df

       label           MSG_DATETIME   P_TIME  p_time
0        1.0  20181101000125600000   00:01.8     1.8
1        1.0  20181101000143000000   00:08.1     8.1
2        1.0  20181101000144700000   00:17.3    17.3
3        1.0  20181101000241200000   00:06.8     6.8
4        1.0  20181101000248600000   00:10.4    10.4
5        1.0  20181101000817200000   00:06.2     6.2
6        1.0  20181101000823300000   00:11.0    11.0
7        1.0  20181101000955200000   00:13.9    13.9
8        1.0  20181101001403800000   00:09.7     9.7
9        1.0  20181101001528400000   00:08.9     8.9
10       1.0  20181101001618400000   00:14.0    14.0
11       1.0  20181101001624600000   00:08.1     8.1
12       1.0  20181101001642700000   00:11.1    11.1
13       1.0  20181101001657100000   00:10.7    10.7
14       1.0  20181101002122300000   00:06.6     6.6
15       1.0  20181101002351300000   00:17.5    17.5
16       1.0  20181101002407400000   00:13.5    13.5
17       1.0  20181101002509500000   00:10.7    10.7
18       1.0  20181101002820200000   00:11.8    11.8
19       1.0  20181101002833300000   00:01.6     1.6
20       1.0  20181101002937000000   00:13.4    13.4
21       1.0  20181101003131400000   00:09.1     9.1
22       1.0  20181101003142400000   00:07.8     7.8
23       1.0  20181101003220300000   00:13.1    13.1
24       1.0  20181101003400800000   00:10.4    10.4
25       1.0  20181101003443900000   00:04.7     4.7
26       1.0  20181101003445000000   00:11.0    11.0
27       1.0  20181101003547400000   00:13.9    13.9
28       1.0  20181101003549200000   00:07.3     7.3
29       1.0  20181101004137300000   00:10.4    10.4
...      ...                    ...      ...     ...
43200    1.0  20181130233211100000   00:08.2     8.2
43201    1.0  20181130233501200000   00:13.2    13.2
43202    1.0  20181130233533600000   00:19.8    19.8
43203    0.0  20181130233609200000   00:20.7    20.7
43204    1.0  20181130233716200000   00:12.5    12.5
43205    0.0  20181130233725800000   00:22.0    22.0
43206    1.0  20181130233733100000   00:19.1    19.1
43207    0.0  20181130233819200000   00:29.7    29.7
43208    0.0  20181130233852400000   00:21.8    21.8
43209    1.0  20181130233901500000   00:02.8     2.8
43210    1.0  20181130234116200000   00:10.0    10.0
43211    1.0  20181130234148800000   00:17.7    17.7
43212    1.0  20181130234213500000   00:10.1    10.1
43213    1.0  20181130234228100000   00:16.1    16.1
43214    0.0  20181130234425100000   00:24.2    24.2
43215    1.0  20181130234633800000   00:18.0    18.0
43216    0.0  20181130234638900000   00:28.3    28.3
43217    0.0  20181130234745000000   00:20.8    20.8
43218    1.0  20181130235206600000   00:19.8    19.8
43219    1.0  20181130235253800000   00:17.4    17.4
43220    0.0  20181130235342200000   00:23.1    23.1
43221    0.0  20181130235556800000   00:21.4    21.4
43222    1.0  20181130235649200000   00:15.1    15.1
43223    0.0  20181130235706300000   00:21.6    21.6
43224    1.0  20181130235708100000   00:14.9    14.9
43225    0.0  20181130235727200000   00:26.5    26.5
43226    1.0  20181130235748100000   00:19.6    19.6
43227    0.0  20181130235834100000   00:22.0    22.0
43228    0.0  20181130235853100000   00:25.8    25.8
43229    1.0  20181130235933400000   00:15.1    15.1

[43230 rows x 4 columns]

In [114]:
q=(df['MSG_DATETIME'][0].replace('00000',''))

'201811010001256 '